frontend/app/(app)/_layout.js, frontend/app/(app)/index.js, frontend/app/(app)/profile.js
Se implementaron el safe area view para el notch/dynamic iisland y animacion en la navegacion del app
=> Dev ulloa navegacion animaciones

backend/docs/API.md, backend/src/controllers/product.controller.js, backend/src/routes/admin.routes.js, backend/src/routes/product.routes.js, backend/src/services/product.service.js
- **Se agregó el endpoint GET /products  para obtener el listado de productos:**
- Si el usuario es administrador, se devuelven todos los productos.
- Si el usuario es cliente, solo se devuelven los productos activos.
- Por seguridad, el ID del usuario que creó el producto no se envía a los clientes.
- Se renombró el controlador getAllProducts a getAllProductosPaginacion para mayor claridad y evitar conflictos con el nuevo endpoint getAllProducts, que devuelve el listado general sin paginación.
🔹 Se actualizaron admin.routes.js y product.routes.js para evitar conflictos de importación.
🔹 Se creó la función getProducts en product.services.js, encargada de la lógica del nuevo endpoint.
**Notas:**
_Estas modificaciones mejoran la organización del código, evitan colisiones de nombres y …
=> Obtener listado general de productos agregado, GET /products

frontend/app/(app)/_layout.js, frontend/app/(app)/index.js, frontend/app/(app)/profile.js, frontend/app/(appAdmin)/_layout.js, frontend/app/(appAdmin)/adminDashboard.js, frontend/app/(appAdmin)/profile.js, frontend/app/(auth)/login.js, frontend/app/(auth)/register.js, frontend/app/_layout.js, frontend/app/components/ConfirmationDialog.js, frontend/app/config/index.js, frontend/app/context/AuthContext.js
Se corrigio el layout de admin, admin, login y register, se quito el header de appAdmin y cuando eres admin  y te logueas te manda directamenre al adminDashboard, tambien se corrigio el error de idUserType en el login
=> Fix layout scrolls

.gitignore, backend/.gitignore, backend/docs/API.md, backend/package.json, backend/src/app.js, backend/src/controllers/admin.controller.js, backend/src/controllers/product.controller.js, backend/src/middlewares/upload.middleware.js, backend/src/middlewares/validateInput.js, backend/src/routes/admin.routes.js, backend/src/routes/product.routes.js
Este pull request introduce nuevas funcionalidades y actualizaciones en la API, enfocándose específicamente en la gestión de imágenes de productos, funcionalidad de búsqueda y obtención de productos populares. Además, se ha actualizado la documentación para reflejar estos cambios.
1. **Endpoints de Imagen de Producto:**
- **GET /api/products/:id/image**: Recupera la imagen de un producto específico.
- **POST /api/admin/products/:id/image**: Sube una imagen para un producto específico. Este endpoint requiere privilegios de administrador y soporta `multipart/form-data`.
2. **Funcionalidad de Búsqueda:**
- **GET /api/products/search**: Permite a los usuarios buscar productos utilizando varios filtros como nombre, tipo, rango de precios y estado. Soporta paginación.
3. **Productos …
=> Endpoints de Imagen de Producto, Búsqueda, Populares

frontend/app/(appAdmin)/_layout.js, frontend/app/(appAdmin)/profile.js, frontend/app/(appAdmin)/profile/editEmail.js
=> edit email admin

backend/docs/API.md, backend/src/controllers/product.controller.js, backend/src/routes/product.routes.js, backend/src/services/product.service.js
Se implementa el Endpoint **GET /products/{id}**, para obtener los detalles de un producto mediante `idProduct`
- Se excluye `idUserAdded` en la respuesta para clientes.
- Si el usuario es administrador, se devuelven todos los productos.
- Si el usuario es cliente, solo se devuelven los productos activos
**Notas:**
Documentación API.md actualizada.
=> Feature:  GET /products/{id}

backend/docs/API.md, backend/src/app.js, backend/src/controllers/shippingAddress.controller.js, backend/src/middlewares/validateInput.js, backend/src/routes/shippingAddress.routes.js, backend/src/services/shippingAddress.service.js
Fueron agregados lo endpoints:
```
GET /api/shipping-address
```
```
POST /api/shipping-address
```
- Solo los usuarios activos (tanto clientes como administradores) pueden agregar nuevas direcciones.
- Todos los campos son obligatorios.
- El campo houseNumber puede ser un número entero de hasta 5 dígitos.
- Se valida que el usuario no tenga una dirección activa previamente registrada al momento de crear una nueva dirección.
- backend/src/controllers/shippingAddress.controller.js
- Añadido controlador para manejar la creación y obtención de direcciones de envío.
- backend/src/routes/shippingAddress.routes.js
- Añadidas rutas para manejar las solicitudes de direcciones de envío.
- backend/src/services/shippingAddress.service.js
- Añadido servicio para interactuar con la base de datos y …
=> ENDPOINTS POST Y GET address agregados

frontend/app/(appAdmin)/_layout.js, frontend/app/(appAdmin)/profile.js, frontend/app/(appAdmin)/profile/editPassword.js, frontend/app/api/ApiService.js, frontend/app/api/AuthService.js
pantalla para hacer cambio de contraseña desde el admin dashboard
=> edit password screen

frontend/app/(appAdmin)/_layout.js, frontend/app/(appAdmin)/product/[id].js
ocultar la barra de navegacion inferior de las pantallas de editar producto y añadir producto
=> ocultar navbar de la pantalla de editar producto y añadir producto

backend/src/routes/product.routes.js
- Las rutas dinámicas `api/products/` y `api/products/{:id}` fueron definidas al final. 
- Ahora se procesan antes la rutas mas especificas.
- fueron probados los endpoints pertenecientes a **products** con los que existía conflicto.
=> Correcion rutas GET products/details

backend/docs/API.md, backend/src/controllers/order.controller.js, backend/src/routes/order.routes.js, backend/src/services/order.service.js
- Endpoint para busqueda de ordenes, validación y paginación.
- Actualización en `API.md`.
=> order search endpoint

backend/docs/API.md, backend/src/controllers/product.controller.js, backend/src/routes/product.routes.js
```
PUT /api/products/{id}/user/personalization
```
```
GET /api/products/{id}/user/personalizations
```
```
PACTH /api/products/{idProduct}/user/personalization/{idProductPersonalization}/status
```
En cada una se excluye **`idUserAdded `** de la respuesta.
Se actualizo la documentación con los nuevos cambios y correcciones en los nombres de las rutas administrativas de customización.
=> Rutas de customizacion para usuario agregadas y documentadas

backend/docs/API.md, backend/src/controllers/cart.controller.js, backend/src/middlewares/validateInput.js, backend/src/routes/cart.routes.js, backend/src/services/cart.service.js
```
/api/cart/items/addOneItem/{idProduct}
```
- Agrega **una unidad** del producto especificado, al carrito de compras para un usuario.
- En caso de que el producto no exista en el carrito, lo añade con la cantidad inicial de 1
- Si el producto ya existe en el carrito de compras, incrementa la cantidad en 1 hasta un máximo de 100 unidades por producto.
- Se considera como parámetro de la ruta `idProduct`
_Documentación API.md actualizada_.
=> add One product - Endpoint

backend/docs/API.md, backend/src/controllers/adminOrder.controller.js, backend/src/routes/admin.routes.js
- Endpoint de Admin: PATCH /admin/order/:id
- Documentación en `API.md`
- Nota: Consultar estados de orden posibles en Prisma Studio.
=> Admin Endpoint: Patch order status + Docs

backend/src/controllers/product.controller.js
- Posibilita el cambio de status en frontend
- El status de la customización es incluido en la respuesta.
=> Las customizaciones inactivas ahora son incluidas

backend/docs/API.md, backend/src/controllers/cart.controller.js, backend/src/routes/admin.routes.js, backend/src/routes/cart.routes.js, backend/src/services/cart.service.js
`GET`
```
/cart/user
```
**Descripción:**
Obtiene todos los carritos (activos e inactivos) que pertenecen al usuario autenticado, incluyendo sus productos activos.
`GET`
```
admin/cart/user/{userId}
```
**Descripción:**
Permite a un administrador consultar todos los carritos (activos e inactivos) de cualquier usuario específico, junto con sus productos activos.
=> Endpoints para buscar carritos por userId y obtener carritos para usuarios autenticados

backend/docs/API.md, backend/src/controllers/product.controller.js, backend/src/routes/product.routes.js
Se implementaron nuevo tres endpoints relacionados con la gestión de personalizaciones aplicadas a productos dentro del carrito de un usuario. Los cambios aseguran integridad de datos, validación de propiedad del recurso y correcta interacción con el modelo Prisma.
Endpoints actualizados:
`PUT`
```
/api/products/cart/items/personalizations
```
- Asigna una personalización específica a un producto del carrito.
- Se validan: existencia del producto, pertenencia del carrito al usuario y correspondencia del producto con la personalización.
- Si ya existe la relación, se reactiva. Si no, se crea una nueva.
`GET`
```
api/cart/items/personalizations/{:idItemCart}
```
- Recupera todas las personalizaciones asociadas a un producto del carrito.
- Se verifica que el producto pertenezca al usuario …
=> Endpoints para asignar y gestionar personalizaciones para un producto en el carrito de compras

backend/docs/API.md, backend/src/controllers/order.controller.js, backend/src/routes/order.routes.js, backend/src/services/order.service.js
`GET`
```
/api/orders/datails
```
Permite a un usuario autenticado recuperar todos sus pedidos con información detallada. La respuesta incluye datos del pedido, carrito asociado, productos comprados, tipo de pago, tipo de envío y estado actual del pedido.
=> Endpoint para obtener ordenes detalladas de un usuario autenticado

backend/src/services/order.service.js
```
/api/orders/{id}
```
- Ahora las personalizaciones son recuperadas y asignadas junto a los producto a reordenar
=> Personlizaciones de pedido a reordenar agregadas

backend/docs/API.md, backend/src/controllers/shippingAddress.controller.js, backend/src/routes/shippingAddress.routes.js, backend/src/services/shippingAddress.service.js
`GET`
```
/api/shipping-address/last
```
- Obtiene la ultima dirección registrada del usuario
- Incluye datos como: 
- `idLocation`, Calle, Numero, Colonia, Código Postal, Status: activo/inactivo
- La dirección es recuperada siempre y cuando este registrada, sin importar este activa o no.
=> Endpoint obtener la ultima dirección registrada de un usuario

frontend/app/(auth)/register.js
se arreglo el view del register
=> Se arreglo el padding en el view de register

backend/docs/API.md, backend/src/controllers/cart.controller.js, backend/src/controllers/shippingAddress.controller.js, backend/src/middlewares/validateInput.js, backend/src/routes/shippingAddress.routes.js, backend/src/services/cart.service.js, backend/src/services/shippingAddress.service.js
```
/api/shipping-address/all
```
- Obtiene todas la direcciones de un usuario registradas, independientemente si están activas o no
- Se incluye su status
**Notas**:
- El limite global para del carrito de compras fue cambiado a un máximo de 30 unidades.
=> Endpoint para obtener todas la direcciones registradas para un usuario

backend/docs/API.md, backend/src/controllers/adminOrder.controller.js, backend/src/middlewares/validateInput.js, backend/src/routes/admin.routes.js, backend/src/services/order.service.js
```
/api/admin/orders/by-products
```
- Recupera todos los pedidos con los productos indicados en la consulta
- Enfocado en uso administrativo
```
api/admin/orders/by-products?product_id=1&product_id=2
```
=> Endpoint para filtrar pedidos por productos agregado

backend/docs/API.md, backend/package-lock.json, backend/package.json, backend/src/controllers/admin.controller.js, backend/src/controllers/adminOrderNotification.controller.js, backend/src/controllers/adminOrderNotification.js, backend/src/controllers/product.controller.js, backend/src/middlewares/upload.middleware.js, backend/src/routes/admin.routes.js, backend/src/services/notification.service.js, backend/src/services/order.service.js, backend/src/services/product.service.js
- Notificaciones a administradores en nuevos pedidos
- Conversion a jpg en endpoint de imagenes de productos
=> admin notifications + image upload fix
